/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as configCmd } from './commands/config.ts';
import type { command as configGetCmd } from './commands/config/get.ts';
import type { command as configInitCmd } from './commands/config/init.ts';
import type { command as configSetCmd } from './commands/config/set.ts';
import type { command as configSetDefaultregionCmd } from './commands/config/set/default-region.ts';
import type { command as configSetProfileCmd } from './commands/config/set/profile.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'config': {
      parents: {};
      rootOptions: {};
    };
    'config get': {
      parents: {
        'config': { options: InferForwardedOptions<typeof configCmd.options>; params: InferParams<typeof configCmd.params> };
      };
      rootOptions: {};
    };
    'config init': {
      parents: {
        'config': { options: InferForwardedOptions<typeof configCmd.options>; params: InferParams<typeof configCmd.params> };
      };
      rootOptions: {};
    };
    'config set': {
      parents: {
        'config': { options: InferForwardedOptions<typeof configCmd.options>; params: InferParams<typeof configCmd.params> };
      };
      rootOptions: {};
    };
    'config set default-region': {
      parents: {
        'config': { options: InferForwardedOptions<typeof configCmd.options>; params: InferParams<typeof configCmd.params> };
        'config set': { options: InferForwardedOptions<typeof configSetCmd.options>; params: InferParams<typeof configSetCmd.params> };
      };
      rootOptions: {};
    };
    'config set profile': {
      parents: {
        'config': { options: InferForwardedOptions<typeof configCmd.options>; params: InferParams<typeof configCmd.params> };
        'config set': { options: InferForwardedOptions<typeof configSetCmd.options>; params: InferParams<typeof configSetCmd.params> };
      };
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'config': {
      segment: { kind: 'literal', value: 'config' },
      command: { path: 'config', load: () => import('./commands/config.ts').then((m) => m.command) },
      literalChildren: {
        'get': {
          segment: { kind: 'literal', value: 'get' },
          command: { path: 'config get', load: () => import('./commands/config/get.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'init': {
          segment: { kind: 'literal', value: 'init' },
          command: { path: 'config init', load: () => import('./commands/config/init.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'set': {
          segment: { kind: 'literal', value: 'set' },
          command: { path: 'config set', load: () => import('./commands/config/set.ts').then((m) => m.command) },
          literalChildren: {
            'default-region': {
              segment: { kind: 'literal', value: 'default-region' },
              command: { path: 'config set default-region', load: () => import('./commands/config/set/default-region.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
            'profile': {
              segment: { kind: 'literal', value: 'profile' },
              command: { path: 'config set profile', load: () => import('./commands/config/set/profile.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
