/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen — do not edit by hand.
import type { InferForwardedOptions, RuntimeNode } from '#index.ts';
import type { command as alphaCmd } from './commands/alpha.ts';

declare module '#index.ts' {
  interface CommandRegistry {
    'alpha': {
      parents: {};
      rootOptions: {};
    };
    'alpha sub': {
      parents: {
        'alpha': { options: InferForwardedOptions<typeof alphaCmd.options>; params: {} };
      };
      rootOptions: {};
    };
    'beta': {
      parents: {};
      rootOptions: {};
    };
    'beta leaf': {
      parents: {
        'beta': { options: {}; params: {} };
      };
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', optionNames: [{ name: 'verbose', type: 'boolean' }], paramNames: [], load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'alpha': {
      segment: { kind: 'literal', value: 'alpha' },
      command: { path: 'alpha', optionNames: [{ name: 'name', type: 'string', forwardToChildren: true }], paramNames: [], load: () => import('./commands/alpha.ts').then((m) => m.command) },
      literalChildren: {
        'sub': {
          segment: { kind: 'literal', value: 'sub' },
          command: { path: 'alpha sub', optionNames: [{ name: 'flag', type: 'boolean' }], paramNames: [], load: () => import('./commands/alpha/sub.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'beta': {
      segment: { kind: 'literal', value: 'beta' },
      command: { path: 'beta', optionNames: [{ name: 'n', type: 'string' }], paramNames: [], load: () => import('./commands/beta.ts').then((m) => m.command) },
      literalChildren: {
        'leaf': {
          segment: { kind: 'literal', value: 'leaf' },
          command: { path: 'beta leaf', optionNames: [], paramNames: [], load: () => import('./commands/beta/leaf.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
  },
  paramChild: null,
};
