/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferSchemas, RuntimeNode } from '@repo/core';
import type { command as adminCmd } from './commands/admin.ts';
import type { command as adminUsersBanCmd } from './commands/admin/users/ban.ts';
import type { command as adminUsersCmd } from './commands/admin/users.ts';
import type { command as deployCmd } from './commands/deploy.ts';
import type { command as usersCmd } from './commands/users.ts';
import type { command as usersCreateCmd } from './commands/users/create.ts';
import type { command as usersIdCmd } from './commands/users/[id].ts';
import type { command as usersIdEditCmd } from './commands/users/[id]/edit.ts';
import type { command as usersListCmd } from './commands/users/list.ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'admin': {
      parents: {};
      root: { options: {} };
    };
    'admin users': {
      parents: {
        'admin': { options: InferSchemas<typeof adminCmd.options>; params: {} };
      };
      root: { options: {} };
    };
    'admin users ban': {
      parents: {
        'admin': { options: InferSchemas<typeof adminCmd.options>; params: {} };
        'admin users': { options: {}; params: {} };
      };
      root: { options: {} };
    };
    'deploy': {
      parents: {};
      root: { options: {} };
    };
    'users': {
      parents: {};
      root: { options: {} };
    };
    'users create': {
      parents: {
        'users': { options: InferSchemas<typeof usersCmd.options>; params: {} };
      };
      root: { options: {} };
    };
    'users list': {
      parents: {
        'users': { options: InferSchemas<typeof usersCmd.options>; params: {} };
      };
      root: { options: {} };
    };
    'users [id]': {
      parents: {
        'users': { options: InferSchemas<typeof usersCmd.options>; params: {} };
      };
      root: { options: {} };
    };
    'users [id] edit': {
      parents: {
        'users': { options: InferSchemas<typeof usersCmd.options>; params: {} };
        'users [id]': { options: {}; params: InferSchemas<typeof usersIdCmd.params> };
      };
      root: { options: {} };
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'admin': {
      segment: { kind: 'literal', value: 'admin' },
      command: { path: 'admin', optionNames: [{ name: 'role', type: 'string' }], paramNames: [], load: () => import('./commands/admin.ts').then((m) => m.command) },
      literalChildren: {
        'users': {
          segment: { kind: 'literal', value: 'users' },
          command: { path: 'admin users', optionNames: [], paramNames: [], load: () => import('./commands/admin/users.ts').then((m) => m.command) },
          literalChildren: {
            'ban': {
              segment: { kind: 'literal', value: 'ban' },
              command: { path: 'admin users ban', optionNames: [{ name: 'reason', type: 'string' }], paramNames: [], load: () => import('./commands/admin/users/ban.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'deploy': {
      segment: { kind: 'literal', value: 'deploy' },
      command: { path: 'deploy', optionNames: [{ name: 'env', type: 'string' }], paramNames: [], load: () => import('./commands/deploy.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'users': {
      segment: { kind: 'literal', value: 'users' },
      command: { path: 'users', optionNames: [{ name: 'workspace', type: 'string' }], paramNames: [], load: () => import('./commands/users.ts').then((m) => m.command) },
      literalChildren: {
        'create': {
          segment: { kind: 'literal', value: 'create' },
          command: { path: 'users create', optionNames: [{ name: 'email', type: 'string' }], paramNames: [], load: () => import('./commands/users/create.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: { path: 'users list', optionNames: [{ name: 'limit', type: 'string' }], paramNames: [], load: () => import('./commands/users/list.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'id' },
        command: { path: 'users [id]', optionNames: [], paramNames: ['id'], load: () => import('./commands/users/[id].ts').then((m) => m.command) },
        literalChildren: {
          'edit': {
            segment: { kind: 'literal', value: 'edit' },
            command: { path: 'users [id] edit', optionNames: [{ name: 'mode', type: 'string' }], paramNames: [], load: () => import('./commands/users/[id]/edit.ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
