/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferArgs } from '@repo/core';
import { command as adminCmd, type args as adminCmdArgs } from './commands/admin.ts';
import { command as adminUsersBanCmd, type args as adminUsersBanCmdArgs } from './commands/admin/users/ban.ts';
import { command as adminUsersCmd } from './commands/admin/users.ts';
import { command as deployCmd, type args as deployCmdArgs } from './commands/deploy.ts';
import { command as usersCmd, type args as usersCmdArgs } from './commands/users.ts';
import { command as usersCreateCmd, type args as usersCreateCmdArgs } from './commands/users/create.ts';
import { command as usersIdCmd, type params as usersIdCmdParams } from './commands/users/[id].ts';
import { command as usersIdEditCmd, type args as usersIdEditCmdArgs } from './commands/users/[id]/edit.ts';
import { command as usersListCmd, type args as usersListCmdArgs } from './commands/users/list.ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'admin': {
      own: InferArgs<typeof adminCmdArgs>;
      inherited: {};
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'admin users': {
      own: {};
      inherited: InferArgs<typeof adminCmdArgs>;
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'admin users ban': {
      own: InferArgs<typeof adminUsersBanCmdArgs>;
      inherited: InferArgs<typeof adminCmdArgs>;
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'deploy': {
      own: InferArgs<typeof deployCmdArgs>;
      inherited: {};
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'users': {
      own: InferArgs<typeof usersCmdArgs>;
      inherited: {};
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'users create': {
      own: InferArgs<typeof usersCreateCmdArgs>;
      inherited: InferArgs<typeof usersCmdArgs>;
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'users list': {
      own: InferArgs<typeof usersListCmdArgs>;
      inherited: InferArgs<typeof usersCmdArgs>;
      ctx: {};
      params: {};
      inheritedParams: {};
    };
    'users [id]': {
      own: {};
      inherited: InferArgs<typeof usersCmdArgs>;
      ctx: {};
      params: InferArgs<typeof usersIdCmdParams>;
      inheritedParams: {};
    };
    'users [id] edit': {
      own: InferArgs<typeof usersIdEditCmdArgs>;
      inherited: InferArgs<typeof usersCmdArgs>;
      ctx: {};
      params: {};
      inheritedParams: Pick<InferArgs<typeof usersIdCmdParams>, 'id'>;
    };
  }
}

import type { RuntimeNode } from '@repo/core';
export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'admin': {
      segment: { kind: 'literal', value: 'admin' },
      command: adminCmd,
      literalChildren: {
        'users': {
          segment: { kind: 'literal', value: 'users' },
          command: adminUsersCmd,
          literalChildren: {
            'ban': {
              segment: { kind: 'literal', value: 'ban' },
              command: adminUsersBanCmd,
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'deploy': {
      segment: { kind: 'literal', value: 'deploy' },
      command: deployCmd,
      literalChildren: {},
      paramChild: null,
    },
    'users': {
      segment: { kind: 'literal', value: 'users' },
      command: usersCmd,
      literalChildren: {
        'create': {
          segment: { kind: 'literal', value: 'create' },
          command: usersCreateCmd,
          literalChildren: {},
          paramChild: null,
        },
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: usersListCmd,
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'id' },
        command: usersIdCmd,
        literalChildren: {
          'edit': {
            segment: { kind: 'literal', value: 'edit' },
            command: usersIdEditCmd,
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
