/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferArgs } from '@repo/core';
import { command as adminCmd } from './commands/admin.ts';
import { command as adminUsersBanCmd } from './commands/admin/users/ban.ts';
import { command as adminUsersCmd } from './commands/admin/users.ts';
import { command as deployCmd } from './commands/deploy.ts';
import { command as usersCmd } from './commands/users.ts';
import { command as usersCreateCmd } from './commands/users/create.ts';
import { command as usersIdCmd } from './commands/users/[id].ts';
import { command as usersIdEditCmd } from './commands/users/[id]/edit.ts';
import { command as usersListCmd } from './commands/users/list.ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'admin': {
      parents: {};
      root: { args: {} };
    };
    'admin users': {
      parents: {
        'admin': { args: InferArgs<typeof adminCmd.args>; params: {} };
      };
      root: { args: {} };
    };
    'admin users ban': {
      parents: {
        'admin': { args: InferArgs<typeof adminCmd.args>; params: {} };
        'admin users': { args: {}; params: {} };
      };
      root: { args: {} };
    };
    'deploy': {
      parents: {};
      root: { args: {} };
    };
    'users': {
      parents: {};
      root: { args: {} };
    };
    'users create': {
      parents: {
        'users': { args: InferArgs<typeof usersCmd.args>; params: {} };
      };
      root: { args: {} };
    };
    'users list': {
      parents: {
        'users': { args: InferArgs<typeof usersCmd.args>; params: {} };
      };
      root: { args: {} };
    };
    'users [id]': {
      parents: {
        'users': { args: InferArgs<typeof usersCmd.args>; params: {} };
      };
      root: { args: {} };
    };
    'users [id] edit': {
      parents: {
        'users': { args: InferArgs<typeof usersCmd.args>; params: {} };
        'users [id]': { args: {}; params: InferArgs<typeof usersIdCmd.params> };
      };
      root: { args: {} };
    };
  }
}

import type { RuntimeNode } from '@repo/core';
export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'admin': {
      segment: { kind: 'literal', value: 'admin' },
      command: adminCmd,
      literalChildren: {
        'users': {
          segment: { kind: 'literal', value: 'users' },
          command: adminUsersCmd,
          literalChildren: {
            'ban': {
              segment: { kind: 'literal', value: 'ban' },
              command: adminUsersBanCmd,
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'deploy': {
      segment: { kind: 'literal', value: 'deploy' },
      command: deployCmd,
      literalChildren: {},
      paramChild: null,
    },
    'users': {
      segment: { kind: 'literal', value: 'users' },
      command: usersCmd,
      literalChildren: {
        'create': {
          segment: { kind: 'literal', value: 'create' },
          command: usersCreateCmd,
          literalChildren: {},
          paramChild: null,
        },
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: usersListCmd,
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'id' },
        command: usersIdCmd,
        literalChildren: {
          'edit': {
            segment: { kind: 'literal', value: 'edit' },
            command: usersIdEditCmd,
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
