/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@repo/core';
import type { command as generateCmd } from './commands/generate.ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'generate': {
      parents: {};
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'generate': {
      segment: { kind: 'literal', value: 'generate' },
      command: { path: 'generate', load: () => import('./commands/generate.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
