/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferSchemas } from '@repo/core';
import { command as generateCmd } from './commands/generate.ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'generate': {
      parents: {};
      root: { options: {} };
    };
  }
}

import type { RuntimeNode } from '@repo/core';
export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'generate': {
      segment: { kind: 'literal', value: 'generate' },
      command: generateCmd,
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
