/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferSchemas, RuntimeNode } from '@repo/core';

declare module '@repo/core' {
  interface CommandRegistry {
    'generate': {
      parents: {};
      root: { options: {} };
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'generate': {
      segment: { kind: 'literal', value: 'generate' },
      command: { path: 'generate', optionNames: [{ name: 'commands', type: 'string' }, { name: 'out', type: 'string' }, { name: 'core-module', type: 'string' }, { name: 'eager', type: 'boolean' }, { name: 'watch', type: 'boolean' }], paramNames: [], load: () => import('./commands/generate.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
