/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen â do not edit by hand.
import type { InferParams, RuntimeNode } from '@parshjs/core';
import type { command as templatesNameCmd } from './commands/templates/[name].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'init': {
      parents: {};
      rootOptions: {};
    };
    'templates': {
      parents: {};
      rootOptions: {};
    };
    'templates list': {
      parents: {
        'templates': { options: {}; params: {} };
      };
      rootOptions: {};
    };
    'templates [name]': {
      parents: {
        'templates': { options: {}; params: {} };
      };
      rootOptions: {};
    };
    'templates [name] show': {
      parents: {
        'templates': { options: {}; params: {} };
        'templates [name]': { options: {}; params: InferParams<typeof templatesNameCmd.params> };
      };
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', optionNames: [], paramNames: [], load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'init': {
      segment: { kind: 'literal', value: 'init' },
      command: { path: 'init', optionNames: [{ name: 'name', type: 'string' }, { name: 'template', type: 'string' }, { name: 'yes', type: 'boolean' }], paramNames: [], description: "Interactively scaffold a new project.", load: () => import('./commands/init.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'templates': {
      segment: { kind: 'literal', value: 'templates' },
      command: { path: 'templates', optionNames: [], paramNames: [], description: "Inspect available scaffold templates.", load: () => import('./commands/templates.ts').then((m) => m.command) },
      literalChildren: {
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: { path: 'templates list', optionNames: [], paramNames: [], description: "List available templates.", load: () => import('./commands/templates/list.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'name' },
        command: { path: 'templates [name]', optionNames: [], paramNames: ['name'], description: "Operate on a single template.", load: () => import('./commands/templates/[name].ts').then((m) => m.command) },
        literalChildren: {
          'show': {
            segment: { kind: 'literal', value: 'show' },
            command: { path: 'templates [name] show', optionNames: [], paramNames: [], description: "Show what a template would generate.", load: () => import('./commands/templates/[name]/show.ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
