/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as initCmd } from './commands/init.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as templatesCmd } from './commands/templates.ts';
import type { command as templatesListCmd } from './commands/templates/list.ts';
import type { command as templatesNameCmd } from './commands/templates/[name].ts';
import type { command as templatesNameShowCmd } from './commands/templates/[name]/show.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'init': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'templates': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'templates list': {
      parents: {
        'templates': { options: InferForwardedOptions<typeof templatesCmd.options>; params: InferParams<typeof templatesCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'templates [name]': {
      parents: {
        'templates': { options: InferForwardedOptions<typeof templatesCmd.options>; params: InferParams<typeof templatesCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'templates [name] show': {
      parents: {
        'templates': { options: InferForwardedOptions<typeof templatesCmd.options>; params: InferParams<typeof templatesCmd.params> };
        'templates [name]': { options: InferForwardedOptions<typeof templatesNameCmd.options>; params: InferParams<typeof templatesNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'init': {
      segment: { kind: 'literal', value: 'init' },
      command: { path: 'init', description: "Interactively scaffold a new project.", load: () => import('./commands/init.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'templates': {
      segment: { kind: 'literal', value: 'templates' },
      command: { path: 'templates', description: "Inspect available scaffold templates.", load: () => import('./commands/templates.ts').then((m) => m.command) },
      literalChildren: {
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: { path: 'templates list', description: "List available templates.", load: () => import('./commands/templates/list.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'name' },
        command: { path: 'templates [name]', description: "Operate on a single template.", load: () => import('./commands/templates/[name].ts').then((m) => m.command) },
        literalChildren: {
          'show': {
            segment: { kind: 'literal', value: 'show' },
            command: { path: 'templates [name] show', description: "Show what a template would generate.", load: () => import('./commands/templates/[name]/show.ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
