/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as ec2Cmd } from './commands/ec2.ts';
import type { command as ec2InstancesIdCmd } from './commands/ec2/instances/[id].ts';
import type { command as ec2InstancesIdTagsSetKeyCmd } from './commands/ec2/instances/[id]/tags/set/[key].ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as s3BucketsNameCmd } from './commands/s3/buckets/[name].ts';
import type { command as s3BucketsNameObjectsKeyCmd } from './commands/s3/buckets/[name]/objects/[key].ts';
import type { command as s3Cmd } from './commands/s3.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'configure': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 create': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances list': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] start': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
        'ec2 instances [id]': { options: {}; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] stop': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
        'ec2 instances [id]': { options: {}; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags add': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
        'ec2 instances [id]': { options: {}; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags set [key]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
        'ec2 instances [id]': { options: {}; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags set [key] [value]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: {} };
        'ec2 instances [id]': { options: {}; params: InferParams<typeof ec2InstancesIdCmd.params> };
        'ec2 instances [id] tags set [key]': { options: {}; params: InferParams<typeof ec2InstancesIdTagsSetKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets list': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name]': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] create': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
        's3 buckets [name]': { options: {}; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects list': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
        's3 buckets [name]': { options: {}; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key]': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
        's3 buckets [name]': { options: {}; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key] get': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
        's3 buckets [name]': { options: {}; params: InferParams<typeof s3BucketsNameCmd.params> };
        's3 buckets [name] objects [key]': { options: {}; params: InferParams<typeof s3BucketsNameObjectsKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key] put': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: {} };
        's3 buckets [name]': { options: {}; params: InferParams<typeof s3BucketsNameCmd.params> };
        's3 buckets [name] objects [key]': { options: {}; params: InferParams<typeof s3BucketsNameObjectsKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', optionNames: [{ name: 'identity', type: 'string', forwardToChildren: true, description: "AWS account identity (required for every command)." }, { name: 'region', type: 'string', forwardToChildren: true, description: "AWS region. Defaults to eu-west-2.", aliases: ["r"] }], paramNames: [], load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'configure': {
      segment: { kind: 'literal', value: 'configure' },
      command: { path: 'configure', optionNames: [{ name: 'access-key', type: 'string' }, { name: 'secret-key', type: 'string' }], paramNames: [], description: "Persist access/secret keys to disk for later use.", load: () => import('./commands/configure.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'ec2': {
      segment: { kind: 'literal', value: 'ec2' },
      command: { path: 'ec2', optionNames: [{ name: 'askConfirmation', type: 'boolean', forwardToChildren: true, description: "Prompt before destructive EC2 operations." }], paramNames: [], description: "Manage EC2 instances.", load: () => import('./commands/ec2.ts').then((m) => m.command) },
      literalChildren: {
        'create': {
          segment: { kind: 'literal', value: 'create' },
          command: { path: 'ec2 create', optionNames: [{ name: 'name', type: 'string' }, { name: 'cpuCount', type: 'string' }], paramNames: [], description: "Create a new EC2 instance.", load: () => import('./commands/ec2/create.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'instances': {
          segment: { kind: 'literal', value: 'instances' },
          command: null,
          literalChildren: {
            'list': {
              segment: { kind: 'literal', value: 'list' },
              command: { path: 'ec2 instances list', optionNames: [], paramNames: [], description: "List EC2 instances.", load: () => import('./commands/ec2/instances/list.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: {
            segment: { kind: 'param', name: 'id' },
            command: { path: 'ec2 instances [id]', optionNames: [], paramNames: ['id'], description: "Operate on a single EC2 instance.", load: () => import('./commands/ec2/instances/[id].ts').then((m) => m.command) },
            literalChildren: {
              'start': {
                segment: { kind: 'literal', value: 'start' },
                command: { path: 'ec2 instances [id] start', optionNames: [], paramNames: [], description: "Start a stopped EC2 instance.", load: () => import('./commands/ec2/instances/[id]/start.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'stop': {
                segment: { kind: 'literal', value: 'stop' },
                command: { path: 'ec2 instances [id] stop', optionNames: [{ name: 'force', type: 'boolean' }], paramNames: [], description: "Stop a running EC2 instance.", load: () => import('./commands/ec2/instances/[id]/stop.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'tags': {
                segment: { kind: 'literal', value: 'tags' },
                command: null,
                literalChildren: {
                  'add': {
                    segment: { kind: 'literal', value: 'add' },
                    command: { path: 'ec2 instances [id] tags add', optionNames: [{ name: 'key', type: 'string' }, { name: 'value', type: 'string' }], paramNames: [], description: "Add a tag to an EC2 instance.", load: () => import('./commands/ec2/instances/[id]/tags/add.ts').then((m) => m.command) },
                    literalChildren: {},
                    paramChild: null,
                  },
                  'set': {
                    segment: { kind: 'literal', value: 'set' },
                    command: null,
                    literalChildren: {},
                    paramChild: {
                      segment: { kind: 'param', name: 'key' },
                      command: { path: 'ec2 instances [id] tags set [key]', optionNames: [], paramNames: ['key'], hidden: true, load: () => import('./commands/ec2/instances/[id]/tags/set/[key].ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: {
                        segment: { kind: 'param', name: 'value' },
                        command: { path: 'ec2 instances [id] tags set [key] [value]', optionNames: [], paramNames: ['value'], description: "Set a tag on an EC2 instance via positional key and value.", load: () => import('./commands/ec2/instances/[id]/tags/set/[key]/[value].ts').then((m) => m.command) },
                        literalChildren: {},
                        paramChild: null,
                      },
                    },
                  },
                },
                paramChild: null,
              },
            },
            paramChild: null,
          },
        },
      },
      paramChild: null,
    },
    's3': {
      segment: { kind: 'literal', value: 's3' },
      command: { path: 's3', optionNames: [{ name: 'profile', type: 'string', forwardToChildren: true, description: "AWS profile to use for S3 calls." }], paramNames: [], description: "Manage S3 buckets and objects.", load: () => import('./commands/s3.ts').then((m) => m.command) },
      literalChildren: {
        'buckets': {
          segment: { kind: 'literal', value: 'buckets' },
          command: null,
          literalChildren: {
            'list': {
              segment: { kind: 'literal', value: 'list' },
              command: { path: 's3 buckets list', optionNames: [], paramNames: [], description: "List S3 buckets.", load: () => import('./commands/s3/buckets/list.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: {
            segment: { kind: 'param', name: 'name' },
            command: { path: 's3 buckets [name]', optionNames: [], paramNames: ['name'], description: "Operate on a single bucket.", load: () => import('./commands/s3/buckets/[name].ts').then((m) => m.command) },
            literalChildren: {
              'create': {
                segment: { kind: 'literal', value: 'create' },
                command: { path: 's3 buckets [name] create', optionNames: [{ name: 'public', type: 'boolean' }], paramNames: [], description: "Create a new S3 bucket.", load: () => import('./commands/s3/buckets/[name]/create.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'objects': {
                segment: { kind: 'literal', value: 'objects' },
                command: null,
                literalChildren: {
                  'list': {
                    segment: { kind: 'literal', value: 'list' },
                    command: { path: 's3 buckets [name] objects list', optionNames: [{ name: 'prefix', type: 'string' }], paramNames: [], description: "List objects in a bucket.", load: () => import('./commands/s3/buckets/[name]/objects/list.ts').then((m) => m.command) },
                    literalChildren: {},
                    paramChild: null,
                  },
                },
                paramChild: {
                  segment: { kind: 'param', name: 'key' },
                  command: { path: 's3 buckets [name] objects [key]', optionNames: [], paramNames: ['key'], description: "Operate on a single object.", load: () => import('./commands/s3/buckets/[name]/objects/[key].ts').then((m) => m.command) },
                  literalChildren: {
                    'get': {
                      segment: { kind: 'literal', value: 'get' },
                      command: { path: 's3 buckets [name] objects [key] get', optionNames: [], paramNames: [], description: "Download an object.", load: () => import('./commands/s3/buckets/[name]/objects/[key]/get.ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: null,
                    },
                    'put': {
                      segment: { kind: 'literal', value: 'put' },
                      command: { path: 's3 buckets [name] objects [key] put', optionNames: [{ name: 'body', type: 'string' }], paramNames: [], description: "Upload an object.", load: () => import('./commands/s3/buckets/[name]/objects/[key]/put.ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: null,
                    },
                  },
                  paramChild: null,
                },
              },
            },
            paramChild: null,
          },
        },
      },
      paramChild: null,
    },
    'status': {
      segment: { kind: 'literal', value: 'status' },
      command: { path: 'status', optionNames: [], paramNames: [], description: "Show resolved configuration: env vars and on-disk credentials.", load: () => import('./commands/status.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
