/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as configureCmd } from './commands/configure.ts';
import type { command as ec2Cmd } from './commands/ec2.ts';
import type { command as ec2CreateCmd } from './commands/ec2/create.ts';
import type { command as ec2InstancesIdCmd } from './commands/ec2/instances/[id].ts';
import type { command as ec2InstancesIdStartCmd } from './commands/ec2/instances/[id]/start.ts';
import type { command as ec2InstancesIdStopCmd } from './commands/ec2/instances/[id]/stop.ts';
import type { command as ec2InstancesIdTagsAddCmd } from './commands/ec2/instances/[id]/tags/add.ts';
import type { command as ec2InstancesIdTagsSetKeyCmd } from './commands/ec2/instances/[id]/tags/set/[key].ts';
import type { command as ec2InstancesIdTagsSetKeyValueCmd } from './commands/ec2/instances/[id]/tags/set/[key]/[value].ts';
import type { command as ec2InstancesListCmd } from './commands/ec2/instances/list.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as s3BucketsListCmd } from './commands/s3/buckets/list.ts';
import type { command as s3BucketsNameCmd } from './commands/s3/buckets/[name].ts';
import type { command as s3BucketsNameCreateCmd } from './commands/s3/buckets/[name]/create.ts';
import type { command as s3BucketsNameObjectsKeyCmd } from './commands/s3/buckets/[name]/objects/[key].ts';
import type { command as s3BucketsNameObjectsKeyGetCmd } from './commands/s3/buckets/[name]/objects/[key]/get.ts';
import type { command as s3BucketsNameObjectsKeyPutCmd } from './commands/s3/buckets/[name]/objects/[key]/put.ts';
import type { command as s3BucketsNameObjectsListCmd } from './commands/s3/buckets/[name]/objects/list.ts';
import type { command as s3Cmd } from './commands/s3.ts';
import type { command as statusCmd } from './commands/status.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'configure': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 create': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances list': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] start': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
        'ec2 instances [id]': { options: InferForwardedOptions<typeof ec2InstancesIdCmd.options>; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] stop': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
        'ec2 instances [id]': { options: InferForwardedOptions<typeof ec2InstancesIdCmd.options>; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags add': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
        'ec2 instances [id]': { options: InferForwardedOptions<typeof ec2InstancesIdCmd.options>; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags set [key]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
        'ec2 instances [id]': { options: InferForwardedOptions<typeof ec2InstancesIdCmd.options>; params: InferParams<typeof ec2InstancesIdCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'ec2 instances [id] tags set [key] [value]': {
      parents: {
        'ec2': { options: InferForwardedOptions<typeof ec2Cmd.options>; params: InferParams<typeof ec2Cmd.params> };
        'ec2 instances [id]': { options: InferForwardedOptions<typeof ec2InstancesIdCmd.options>; params: InferParams<typeof ec2InstancesIdCmd.params> };
        'ec2 instances [id] tags set [key]': { options: InferForwardedOptions<typeof ec2InstancesIdTagsSetKeyCmd.options>; params: InferParams<typeof ec2InstancesIdTagsSetKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets list': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name]': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] create': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
        's3 buckets [name]': { options: InferForwardedOptions<typeof s3BucketsNameCmd.options>; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects list': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
        's3 buckets [name]': { options: InferForwardedOptions<typeof s3BucketsNameCmd.options>; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key]': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
        's3 buckets [name]': { options: InferForwardedOptions<typeof s3BucketsNameCmd.options>; params: InferParams<typeof s3BucketsNameCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key] get': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
        's3 buckets [name]': { options: InferForwardedOptions<typeof s3BucketsNameCmd.options>; params: InferParams<typeof s3BucketsNameCmd.params> };
        's3 buckets [name] objects [key]': { options: InferForwardedOptions<typeof s3BucketsNameObjectsKeyCmd.options>; params: InferParams<typeof s3BucketsNameObjectsKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    's3 buckets [name] objects [key] put': {
      parents: {
        's3': { options: InferForwardedOptions<typeof s3Cmd.options>; params: InferParams<typeof s3Cmd.params> };
        's3 buckets [name]': { options: InferForwardedOptions<typeof s3BucketsNameCmd.options>; params: InferParams<typeof s3BucketsNameCmd.params> };
        's3 buckets [name] objects [key]': { options: InferForwardedOptions<typeof s3BucketsNameObjectsKeyCmd.options>; params: InferParams<typeof s3BucketsNameObjectsKeyCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'configure': {
      segment: { kind: 'literal', value: 'configure' },
      command: { path: 'configure', load: () => import('./commands/configure.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'ec2': {
      segment: { kind: 'literal', value: 'ec2' },
      command: { path: 'ec2', load: () => import('./commands/ec2.ts').then((m) => m.command) },
      literalChildren: {
        'create': {
          segment: { kind: 'literal', value: 'create' },
          command: { path: 'ec2 create', load: () => import('./commands/ec2/create.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'instances': {
          segment: { kind: 'literal', value: 'instances' },
          command: null,
          literalChildren: {
            'list': {
              segment: { kind: 'literal', value: 'list' },
              command: { path: 'ec2 instances list', load: () => import('./commands/ec2/instances/list.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: {
            segment: { kind: 'param', name: 'id' },
            command: { path: 'ec2 instances [id]', load: () => import('./commands/ec2/instances/[id].ts').then((m) => m.command) },
            literalChildren: {
              'start': {
                segment: { kind: 'literal', value: 'start' },
                command: { path: 'ec2 instances [id] start', load: () => import('./commands/ec2/instances/[id]/start.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'stop': {
                segment: { kind: 'literal', value: 'stop' },
                command: { path: 'ec2 instances [id] stop', load: () => import('./commands/ec2/instances/[id]/stop.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'tags': {
                segment: { kind: 'literal', value: 'tags' },
                command: null,
                literalChildren: {
                  'add': {
                    segment: { kind: 'literal', value: 'add' },
                    command: { path: 'ec2 instances [id] tags add', load: () => import('./commands/ec2/instances/[id]/tags/add.ts').then((m) => m.command) },
                    literalChildren: {},
                    paramChild: null,
                  },
                  'set': {
                    segment: { kind: 'literal', value: 'set' },
                    command: null,
                    literalChildren: {},
                    paramChild: {
                      segment: { kind: 'param', name: 'key' },
                      command: { path: 'ec2 instances [id] tags set [key]', load: () => import('./commands/ec2/instances/[id]/tags/set/[key].ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: {
                        segment: { kind: 'param', name: 'value' },
                        command: { path: 'ec2 instances [id] tags set [key] [value]', load: () => import('./commands/ec2/instances/[id]/tags/set/[key]/[value].ts').then((m) => m.command) },
                        literalChildren: {},
                        paramChild: null,
                      },
                    },
                  },
                },
                paramChild: null,
              },
            },
            paramChild: null,
          },
        },
      },
      paramChild: null,
    },
    's3': {
      segment: { kind: 'literal', value: 's3' },
      command: { path: 's3', load: () => import('./commands/s3.ts').then((m) => m.command) },
      literalChildren: {
        'buckets': {
          segment: { kind: 'literal', value: 'buckets' },
          command: null,
          literalChildren: {
            'list': {
              segment: { kind: 'literal', value: 'list' },
              command: { path: 's3 buckets list', load: () => import('./commands/s3/buckets/list.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: {
            segment: { kind: 'param', name: 'name' },
            command: { path: 's3 buckets [name]', load: () => import('./commands/s3/buckets/[name].ts').then((m) => m.command) },
            literalChildren: {
              'create': {
                segment: { kind: 'literal', value: 'create' },
                command: { path: 's3 buckets [name] create', load: () => import('./commands/s3/buckets/[name]/create.ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
              'objects': {
                segment: { kind: 'literal', value: 'objects' },
                command: null,
                literalChildren: {
                  'list': {
                    segment: { kind: 'literal', value: 'list' },
                    command: { path: 's3 buckets [name] objects list', load: () => import('./commands/s3/buckets/[name]/objects/list.ts').then((m) => m.command) },
                    literalChildren: {},
                    paramChild: null,
                  },
                },
                paramChild: {
                  segment: { kind: 'param', name: 'key' },
                  command: { path: 's3 buckets [name] objects [key]', load: () => import('./commands/s3/buckets/[name]/objects/[key].ts').then((m) => m.command) },
                  literalChildren: {
                    'get': {
                      segment: { kind: 'literal', value: 'get' },
                      command: { path: 's3 buckets [name] objects [key] get', load: () => import('./commands/s3/buckets/[name]/objects/[key]/get.ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: null,
                    },
                    'put': {
                      segment: { kind: 'literal', value: 'put' },
                      command: { path: 's3 buckets [name] objects [key] put', load: () => import('./commands/s3/buckets/[name]/objects/[key]/put.ts').then((m) => m.command) },
                      literalChildren: {},
                      paramChild: null,
                    },
                  },
                  paramChild: null,
                },
              },
            },
            paramChild: null,
          },
        },
      },
      paramChild: null,
    },
    'status': {
      segment: { kind: 'literal', value: 'status' },
      command: { path: 'status', load: () => import('./commands/status.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
