/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as DELETECmd } from './commands/DELETE.ts';
import type { command as DELETEUrlCmd } from './commands/DELETE/[url].ts';
import type { command as GETCmd } from './commands/GET.ts';
import type { command as GETUrlCmd } from './commands/GET/[url].ts';
import type { command as HEADCmd } from './commands/HEAD.ts';
import type { command as HEADUrlCmd } from './commands/HEAD/[url].ts';
import type { command as PATCHCmd } from './commands/PATCH.ts';
import type { command as PATCHUrlCmd } from './commands/PATCH/[url].ts';
import type { command as POSTCmd } from './commands/POST.ts';
import type { command as POSTUrlCmd } from './commands/POST/[url].ts';
import type { command as PUTCmd } from './commands/PUT.ts';
import type { command as PUTUrlCmd } from './commands/PUT/[url].ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as urlCmd } from './commands/[url].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'DELETE': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'DELETE [url]': {
      parents: {
        'DELETE': { options: InferForwardedOptions<typeof DELETECmd.options>; params: InferParams<typeof DELETECmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'GET': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'GET [url]': {
      parents: {
        'GET': { options: InferForwardedOptions<typeof GETCmd.options>; params: InferParams<typeof GETCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'HEAD': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'HEAD [url]': {
      parents: {
        'HEAD': { options: InferForwardedOptions<typeof HEADCmd.options>; params: InferParams<typeof HEADCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'PATCH': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'PATCH [url]': {
      parents: {
        'PATCH': { options: InferForwardedOptions<typeof PATCHCmd.options>; params: InferParams<typeof PATCHCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'POST': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'POST [url]': {
      parents: {
        'POST': { options: InferForwardedOptions<typeof POSTCmd.options>; params: InferParams<typeof POSTCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'PUT': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'PUT [url]': {
      parents: {
        'PUT': { options: InferForwardedOptions<typeof PUTCmd.options>; params: InferParams<typeof PUTCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    '[url]': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'DELETE': {
      segment: { kind: 'literal', value: 'DELETE' },
      command: { path: 'DELETE', load: () => import('./commands/DELETE.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'DELETE [url]', load: () => import('./commands/DELETE/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
    'GET': {
      segment: { kind: 'literal', value: 'GET' },
      command: { path: 'GET', load: () => import('./commands/GET.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'GET [url]', load: () => import('./commands/GET/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
    'HEAD': {
      segment: { kind: 'literal', value: 'HEAD' },
      command: { path: 'HEAD', load: () => import('./commands/HEAD.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'HEAD [url]', load: () => import('./commands/HEAD/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
    'PATCH': {
      segment: { kind: 'literal', value: 'PATCH' },
      command: { path: 'PATCH', load: () => import('./commands/PATCH.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'PATCH [url]', load: () => import('./commands/PATCH/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
    'POST': {
      segment: { kind: 'literal', value: 'POST' },
      command: { path: 'POST', load: () => import('./commands/POST.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'POST [url]', load: () => import('./commands/POST/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
    'PUT': {
      segment: { kind: 'literal', value: 'PUT' },
      command: { path: 'PUT', load: () => import('./commands/PUT.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'url' },
        command: { path: 'PUT [url]', load: () => import('./commands/PUT/[url].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
  },
  paramChild: {
    segment: { kind: 'param', name: 'url' },
    command: { path: '[url]', load: () => import('./commands/[url].ts').then((m) => m.command) },
    literalChildren: {},
    paramChild: null,
  },
};
