import type { CommandNode, ExtractedCommand, SourceSegment } from '#types.ts';

export interface EmitOptions {
  /**
   * TS expression for inferring root args, e.g. `"typeof import('../root.ts').rootArgs"`.
   * If omitted, root args contribute `{}` to every command's `ctx.root.args`.
   */
  rootArgsTypeExpr?: string;
  /**
   * Module specifier augmented by the generated `declare module` block and imported
   * for `InferArgs` / `RuntimeNode`. Defaults to `'@parsh/core'`.
   * Override for in-repo dogfooding (e.g., `'@repo/core'`).
   */
  coreModule?: string;
}

function segmentKey(seg: SourceSegment): string {
  return seg.kind === 'literal' ? seg.value : `[${seg.name}]`;
}

function pathStringOf(segments: SourceSegment[]): string {
  return segments.map(segmentKey).join(' ');
}

interface FlatEntry {
  pathString: string;
  cmd: ExtractedCommand;
  /** All ancestor commands (closest-last). */
  ancestorCmds: ExtractedCommand[];
}

function flattenTree(root: CommandNode): FlatEntry[] {
  const out: FlatEntry[] = [];
  function walk(input: { node: CommandNode; ancestorCmds: ExtractedCommand[] }) {
    const cmd = input.node.command;
    let nextAncestorCmds = input.ancestorCmds;
    if (cmd) {
      out.push({
        pathString: pathStringOf(input.node.path.map(parseSegKey)),
        cmd,
        ancestorCmds: input.ancestorCmds,
      });
      nextAncestorCmds = [...input.ancestorCmds, cmd];
    }
    for (const name of [...input.node.literalChildren.keys()].sort()) {
      const child = input.node.literalChildren.get(name);
      if (child) {
        walk({ node: child, ancestorCmds: nextAncestorCmds });
      }
    }
    if (input.node.paramChild) {
      walk({ node: input.node.paramChild, ancestorCmds: nextAncestorCmds });
    }
  }
  walk({ node: root, ancestorCmds: [] });
  return out;
}

function parseSegKey(key: string): SourceSegment {
  if (key.startsWith('[') && key.endsWith(']')) {
    return { kind: 'param', name: key.slice(1, -1) };
  }
  return { kind: 'literal', value: key };
}

function ancestorArgsType(anc: ExtractedCommand): string {
  return anc.argNames.length === 0 ? '{}' : `InferArgs<typeof ${anc.importName}.args>`;
}

function ancestorParamsType(anc: ExtractedCommand): string {
  return anc.paramNames.length === 0 ? '{}' : `InferArgs<typeof ${anc.importName}.params>`;
}

function emitParentsMap(entry: FlatEntry): string {
  if (entry.ancestorCmds.length === 0) {
    return '{}';
  }
  const lines = entry.ancestorCmds.map(
    (anc) =>
      `        '${pathStringOf(anc.segments)}': { args: ${ancestorArgsType(anc)}; params: ${ancestorParamsType(anc)} };`,
  );
  return `{\n${lines.join('\n')}\n      }`;
}

function emitRootBlock(rootArgsTypeExpr: string | undefined): string {
  const argsType = rootArgsTypeExpr ? `InferArgs<${rootArgsTypeExpr}>` : '{}';
  return `{ args: ${argsType} }`;
}

function emitRegistryEntry(opts: {
  entry: FlatEntry;
  rootArgsTypeExpr: string | undefined;
}): string {
  const p = opts.entry.pathString;
  return `    '${p}': {
      parents: ${emitParentsMap(opts.entry)};
      root: ${emitRootBlock(opts.rootArgsTypeExpr)};
    };`;
}

function emitRuntimeNode(opts: { node: CommandNode; indent: string }): string {
  const ind = opts.indent;
  const inner = `${ind}  `;
  const seg = opts.node.segment;
  const segExpr =
    seg === null
      ? 'null'
      : seg.kind === 'literal'
        ? `{ kind: 'literal', value: '${seg.value}' }`
        : `{ kind: 'param', name: '${seg.name}' }`;
  const cmdExpr = opts.node.command ? opts.node.command.importName : 'null';
  const literalKeys = [...opts.node.literalChildren.keys()].sort();
  let lcExpr: string;
  if (literalKeys.length === 0) {
    lcExpr = '{}';
  } else {
    const parts = literalKeys.map((name) => {
      const child = opts.node.literalChildren.get(name)!;
      return `${inner}  '${name}': ${emitRuntimeNode({ node: child, indent: `${inner}  ` })}`;
    });
    lcExpr = `{\n${parts.join(',\n')},\n${inner}}`;
  }
  const pcExpr = opts.node.paramChild
    ? emitRuntimeNode({ node: opts.node.paramChild, indent: inner })
    : 'null';
  return `{
${inner}segment: ${segExpr},
${inner}command: ${cmdExpr},
${inner}literalChildren: ${lcExpr},
${inner}paramChild: ${pcExpr},
${ind}}`;
}

export function emitGeneratedFile(opts: { root: CommandNode; emitOptions: EmitOptions }): string {
  const entries = flattenTree(opts.root);
  const imports = entries
    .map((e) => e.cmd)
    // biome-ignore lint/complexity/useMaxParams: Array.sort comparator is inherently (a, b)
    .sort((a, b) => a.importName.localeCompare(b.importName));

  const coreModule = opts.emitOptions.coreModule ?? '@parsh/core';

  const lines: string[] = [];
  lines.push(
    '/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */',
  );
  lines.push('// AUTOGENERATED by @parsh/codegen — do not edit by hand.');
  lines.push(`import type { InferArgs } from '${coreModule}';`);
  for (const cmd of imports) {
    lines.push(`import { command as ${cmd.importName} } from '${cmd.importSpecifier}';`);
  }
  lines.push('');
  lines.push(`declare module '${coreModule}' {`);
  lines.push('  interface CommandRegistry {');
  for (const e of entries) {
    lines.push(
      emitRegistryEntry({
        entry: e,
        rootArgsTypeExpr: opts.emitOptions.rootArgsTypeExpr,
      }),
    );
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push(`import type { RuntimeNode } from '${coreModule}';`);
  lines.push(
    `export const commandTree: RuntimeNode = ${emitRuntimeNode({ node: opts.root, indent: '' })};`,
  );
  lines.push('');
  return lines.join('\n');
}
