import type { CommandNode, ExtractedCommand, SourceSegment } from '#types.ts';

export interface EmitOptions {
  /**
   * Module specifier augmented by the generated `declare module` block and imported
   * for `InferSchemas` / `RuntimeNode`. Defaults to `'@parsh/core'`.
   * Override for in-repo dogfooding (e.g., `'@repo/core'`).
   */
  coreModule?: string;
}

function segmentKey(seg: SourceSegment): string {
  return seg.kind === 'literal' ? seg.value : `[${seg.name}]`;
}

function pathStringOf(segments: SourceSegment[]): string {
  return segments.map(segmentKey).join(' ');
}

interface FlatEntry {
  pathString: string;
  cmd: ExtractedCommand;
  ancestorCmds: ExtractedCommand[];
}

function flattenTree({
  root,
}: {
  root: CommandNode;
  rootCmd: ExtractedCommand | null;
}): FlatEntry[] {
  const out: FlatEntry[] = [];
  function walk({ node, ancestorCmds }: { node: CommandNode; ancestorCmds: ExtractedCommand[] }) {
    const cmd = node.command;
    const isTreeRoot = node === root;
    let nextAncestorCmds = ancestorCmds;
    if (cmd && !isTreeRoot) {
      out.push({
        pathString: pathStringOf(node.path.map(parseSegKey)),
        cmd,
        ancestorCmds,
      });
      nextAncestorCmds = [...ancestorCmds, cmd];
    }
    for (const name of [...node.literalChildren.keys()].sort()) {
      const child = node.literalChildren.get(name);
      if (child) {
        walk({ node: child, ancestorCmds: nextAncestorCmds });
      }
    }
    if (node.paramChild) {
      walk({ node: node.paramChild, ancestorCmds: nextAncestorCmds });
    }
  }
  walk({ node: root, ancestorCmds: [] });
  return out;
}

function parseSegKey(key: string): SourceSegment {
  if (key.startsWith('[') && key.endsWith(']')) {
    return { kind: 'param', name: key.slice(1, -1) };
  }
  return { kind: 'literal', value: key };
}

function ancestorOptionsType(anc: ExtractedCommand): string {
  return anc.optionNames.length === 0 ? '{}' : `InferSchemas<typeof ${anc.importName}.options>`;
}

function ancestorParamsType(anc: ExtractedCommand): string {
  return anc.paramNames.length === 0 ? '{}' : `InferSchemas<typeof ${anc.importName}.params>`;
}

function emitParentsMap(entry: FlatEntry): string {
  if (entry.ancestorCmds.length === 0) {
    return '{}';
  }
  const lines = entry.ancestorCmds.map(
    (anc) =>
      `        '${pathStringOf(anc.segments)}': { options: ${ancestorOptionsType(anc)}; params: ${ancestorParamsType(anc)} };`,
  );
  return `{\n${lines.join('\n')}\n      }`;
}

function emitRootBlock(rootCmd: ExtractedCommand | null): string {
  const optionsType =
    rootCmd && rootCmd.optionNames.length > 0
      ? `InferSchemas<typeof ${rootCmd.importName}.options>`
      : '{}';
  return `{ options: ${optionsType} }`;
}

function emitRegistryEntry({
  entry,
  rootCmd,
}: {
  entry: FlatEntry;
  rootCmd: ExtractedCommand | null;
}): string {
  const p = entry.pathString;
  return `    '${p}': {
      parents: ${emitParentsMap(entry)};
      root: ${emitRootBlock(rootCmd)};
    };`;
}

function emitRuntimeNode({ node, indent }: { node: CommandNode; indent: string }): string {
  const inner = `${indent}  `;
  const seg = node.segment;
  const segExpr =
    seg === null
      ? 'null'
      : seg.kind === 'literal'
        ? `{ kind: 'literal', value: '${seg.value}' }`
        : `{ kind: 'param', name: '${seg.name}' }`;
  const cmdExpr = node.command ? node.command.importName : 'null';
  const literalKeys = [...node.literalChildren.keys()].sort();
  let lcExpr: string;
  if (literalKeys.length === 0) {
    lcExpr = '{}';
  } else {
    const parts = literalKeys.map((name) => {
      const child = node.literalChildren.get(name)!;
      return `${inner}  '${name}': ${emitRuntimeNode({ node: child, indent: `${inner}  ` })}`;
    });
    lcExpr = `{\n${parts.join(',\n')},\n${inner}}`;
  }
  const pcExpr = node.paramChild
    ? emitRuntimeNode({ node: node.paramChild, indent: inner })
    : 'null';
  return `{
${inner}segment: ${segExpr},
${inner}command: ${cmdExpr},
${inner}literalChildren: ${lcExpr},
${inner}paramChild: ${pcExpr},
${indent}}`;
}

export function emitGeneratedFile({
  root,
  emitOptions,
}: {
  root: CommandNode;
  emitOptions: EmitOptions;
}): string {
  const rootCmd = root.command;
  const entries = flattenTree({ root, rootCmd });
  const importCmds: ExtractedCommand[] = [...entries.map((e) => e.cmd)];
  if (rootCmd) {
    importCmds.push(rootCmd);
  }
  const imports = importCmds
    // biome-ignore lint/complexity/useMaxParams: Array.sort comparator is inherently (a, b)
    .sort((a, b) => a.importName.localeCompare(b.importName));

  const coreModule = emitOptions.coreModule ?? '@parsh/core';

  const lines: string[] = [];
  lines.push(
    '/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */',
  );
  lines.push('// AUTOGENERATED by @parsh/codegen — do not edit by hand.');
  lines.push(`import type { InferSchemas } from '${coreModule}';`);
  for (const cmd of imports) {
    lines.push(`import { command as ${cmd.importName} } from '${cmd.importSpecifier}';`);
  }
  lines.push('');
  lines.push(`declare module '${coreModule}' {`);
  lines.push('  interface CommandRegistry {');
  for (const e of entries) {
    lines.push(emitRegistryEntry({ entry: e, rootCmd }));
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push(`import type { RuntimeNode } from '${coreModule}';`);
  lines.push(
    `export const commandTree: RuntimeNode = ${emitRuntimeNode({ node: root, indent: '' })};`,
  );
  lines.push('');
  return lines.join('\n');
}
