/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as greetCmd } from './commands/greet.ts';
import type { command as rootCmd } from './commands/_root.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'greet': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'greet': {
      segment: { kind: 'literal', value: 'greet' },
      command: { path: 'greet', load: () => import('./commands/greet.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
