/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { RuntimeNode } from '@repo/core';

declare module '@repo/core' {
  interface CommandRegistry {
    'serve': {
      parents: {};
      root: { options: {} };
    };
    'version': {
      parents: {};
      root: { options: {} };
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'serve': {
      segment: { kind: 'literal', value: 'serve' },
      command: { path: 'serve', optionNames: [], paramNames: [], description: "Start the (pretend) HTTP server using validated env vars.", load: () => import('./commands/serve.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'version': {
      segment: { kind: 'literal', value: 'version' },
      command: { path: 'version', optionNames: [], paramNames: [], description: "Print the CLI version. Doesn't read any env var.", load: () => import('./commands/version.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
