/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, RuntimeNode } from '@parshjs/core';
import type { command as serveCmd } from './commands/serve.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'serve': {
      parents: {};
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'serve': {
      segment: { kind: 'literal', value: 'serve' },
      command: { path: 'serve', paramNames: [], description: "Start the (pretend) HTTP server using validated env vars.", load: () => import('./commands/serve.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
