/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parsh/codegen — do not edit by hand.
import type { InferForwardedOptions, InferSchemas, RuntimeNode } from '@repo/core';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as tasksIdCmd } from './commands/tasks/[id].ts';

declare module '@repo/core' {
  interface CommandRegistry {
    'start': {
      parents: {};
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'stats': {
      parents: {};
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks': {
      parents: {};
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks add': {
      parents: {
        'tasks': { options: {}; params: {} };
      };
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks list': {
      parents: {
        'tasks': { options: {}; params: {} };
      };
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks [id]': {
      parents: {
        'tasks': { options: {}; params: {} };
      };
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks [id] done': {
      parents: {
        'tasks': { options: {}; params: {} };
        'tasks [id]': { options: {}; params: InferSchemas<typeof tasksIdCmd.params> };
      };
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
    'tasks [id] remove': {
      parents: {
        'tasks': { options: {}; params: {} };
        'tasks [id]': { options: {}; params: InferSchemas<typeof tasksIdCmd.params> };
      };
      root: { options: InferForwardedOptions<typeof rootCmd.options> };
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', optionNames: [{ name: 'stateFile', type: 'string', forwardToChildren: true, description: "Path to the JSON file backing tasks and sessions." }], paramNames: [], description: "A pomodoro timer with a live Ink countdown.", load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'start': {
      segment: { kind: 'literal', value: 'start' },
      command: { path: 'start', optionNames: [{ name: 'duration', type: 'string' }, { name: 'task', type: 'string' }], paramNames: [], description: "Start a pomodoro session with a live countdown.", load: () => import('./commands/start.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'stats': {
      segment: { kind: 'literal', value: 'stats' },
      command: { path: 'stats', optionNames: [], paramNames: [], description: "Show total pomodoro time and session count.", load: () => import('./commands/stats.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'tasks': {
      segment: { kind: 'literal', value: 'tasks' },
      command: { path: 'tasks', optionNames: [], paramNames: [], description: "Manage pomodoro tasks.", load: () => import('./commands/tasks.ts').then((m) => m.command) },
      literalChildren: {
        'add': {
          segment: { kind: 'literal', value: 'add' },
          command: { path: 'tasks add', optionNames: [{ name: 'title', type: 'string' }], paramNames: [], description: "Add a new task.", load: () => import('./commands/tasks/add.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: { path: 'tasks list', optionNames: [], paramNames: [], description: "List all tasks.", load: () => import('./commands/tasks/list.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: {
        segment: { kind: 'param', name: 'id' },
        command: { path: 'tasks [id]', optionNames: [], paramNames: ['id'], description: "Operate on a single task.", load: () => import('./commands/tasks/[id].ts').then((m) => m.command) },
        literalChildren: {
          'done': {
            segment: { kind: 'literal', value: 'done' },
            command: { path: 'tasks [id] done', optionNames: [], paramNames: [], description: "Mark a task as done.", load: () => import('./commands/tasks/[id]/done.ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
          'remove': {
            segment: { kind: 'literal', value: 'remove' },
            command: { path: 'tasks [id] remove', optionNames: [], paramNames: [], description: "Delete a task.", load: () => import('./commands/tasks/[id]/remove.ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
        },
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
